version: "3.9"

services:
  db:
    image: postgres:15
    container_name: avito2025-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - avito2025_pgdata:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:${DB_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 2s
      timeout: 3s
      retries: 10

  migrate:
    image: postgres:15
    container_name: avito2025-migrations
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./internal/migrations:/migrations
    environment:
      PGPASSWORD: ${DB_PASS}
    entrypoint: >
      sh -c "psql -h ${DB_HOST} -U ${DB_USER} -d ${DB_NAME} -f /migrations/0001_init.sql"


  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: avito2025-app
    depends_on:
      migrate:
        condition: service_completed_successfully
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
    ports:
      - "${APP_PORT}:8080"
    command: ["/pr-reviewer"]


volumes:
  avito2025_pgdata: