services:
  db:
    image: postgres:15
    container_name: avito2025-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - avito2025_pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 2s
      timeout: 3s
      retries: 10

  migrate:
    image: postgres:15
    container_name: avito2025-migrations
    depends_on:
      db:
        condition: service_healthy
    environment:
      PGPASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./internal/migrations:/migrations
    entrypoint: [
      "sh", "-c",
      "psql -h ${DB_HOST} -U ${DB_USER} -d ${DB_NAME} -f /migrations/0001_init.sql"
    ]

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: avito2025-app
    depends_on:
      migrate:
        condition: service_completed_successfully
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
    ports:
      - "8080:8080"
    command: ["/pr-reviewer"]

volumes:
  avito2025_pgdata: